# TW5FontAwesome: Travis Continous Integration
#
# Testing is only done in a very simplistic manner by running a TiddlyWiki
# under Node.js which in turns loads all stuff. If that succeeds, the test
# is considered to be good.
#
# Building runs the --release command on this TiddlyWiki, which then uses
# ThirdFlow's automated release mechnism to generate the release files.
#
# Deploying does three things:
# 1. Uploading the release files to the GitHub Pages for this GitHub project.
# 2. Publishing the package on NPM.
# 3. Drafting a new GitHub release and attaching the release files to it.

language: node_js
node_js: 'node' # latest stable Node.js release

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+*$/

env:
  global:
    - OUTPUT_DIR=editions/release/output
    - GH_PAGES_DIR=gh-pages
    - GH_PAGES_OUTPUT_DIR=$GH_PAGES_DIR/output

cache:
  directories:
    - "node_modules"

before_install:
  # As we only want to update the release files in our GitHub Pages, we
  # need to get the gh-pages branch first. Later, after updating the release
  # files, the deployment will check in the complete gh-pages branch again
  # -- including the updated release files.
  - git clone --branch gh-pages --single-branch --depth 1 https://github.com/$TRAVIS_REPO_SLUG gh-pages

script:
  - if [ -z "$TRAVIS_TAG" ]; then npm test; fi
  - if [ -n "$TRAVIS_TAG" ]; then npm run update; fi
  - npm run release
    # Copy release files to our GitHub Pages for this project.
  - cp $OUTPUT_DIR/fontawesome.tid $GH_PAGES_OUTPUT_DIR
  - cp $OUTPUT_DIR/fontawesome.html $GH_PAGES_OUTPUT_DIR

deploy:
  # Uploads new release files to the GitHub pages of our project...
  - provider: pages
    github-token:
      secure: nUm4FY23wMQeriLJ/SPJkWsA5cdz7y9zZVCI5wh8No6TjZXJKStWrUXdD/LYpix7OHnFNQeAGsNLnF8ShB7j290JaNWzThU9I3K5aTr9Jj8VwPt7g+dQZYFM1CWyKxdlPLDzTPTLespcu+9/Q5CjhyaiLVfcALIuZ3OB/4vbmmjTv1mJl3XiLBtQuPk9/itpn/6KR09CAdI+18DeDqxRGkAkz3v/GBnPrYtzsbV7ExbQz+qrbmKdrZ7Ni/v+Dm+OCBd7gtQWoNstUY2ZHsz2fTRqpXtLbziSgiSQ02LYvQojrQw8v7bkIkxe1eKHGdK3WhtgGi0kH35jK75C6gFAStfwvhVNh5/Nx1WHmTJVU0EFlyocCHDF85mhltQUaYWaqaayuTab9jsZ/65uRv3L9TlaPNrCY8jenmdKjwo5w7M3uvWx6/WrOFMJvInP8howqBMdWlrGZtomqd8uQFhFBJvV1uu9D07tfOPNy2FtVQlVd45+AvZ2LgN1I0v+H0qDo3mtypVdaj5JSzpM/cnEE0ah5yzf4FGSxZiOIhAvPKuRLEEzY5q5e26ztyVVYdmCX+mpiMp4KzzCvwWFHkDxa4O0OjOncl97g7aLAjZbuOM2dgbMKSPd5TMxDm2wZJ6giVw9ZXqY3YtVxmCfHMNILbPj8el+HfCbzYmIxGx1OnY=
    skip_cleanup: true
    keep-history: true
    on:
      repo: $TRAVIS_REPO_SLUG
      tags: true
    local-dir: $GH_PAGES_DIR

  # Publish new release on NPM registry
  - provider: npm
    email: thediveo@gmx.eu
    api_key:
      secure: GRVeRsRPByp507VUjt1p6Ol4v/i9+7CgtI93U6x1qT9xErOKWbqPF15T5DujFgyLb2MT2lypNMTCytk52U4WJumpXPTkd8zwZ5xIQgm9G8oG3VPSukHhMyndg+K6uYfuPZVY/KFc40xzdMbYDmn/xM1X5gW+PX6+gJHPaDqGQW4SlHEXI1utsvEoFTv7NJEJh7CHzwmCN8IScGEn8MnMloXQYYg84I+qczBhHQvqIpw+aJ1uYArc1ct1yRShcd7CLMjJ0YWvsV5Ne3najbdZhEOJNvnyE6NX8Dd0gncXKvhHyRWy91bSW7TgL9EHtCWcc6ACbLzaYspZCfUiBT2r7Bc2x6O+WyuJNBg0O4p7A2bLD4LJLVvBG9NXNDERtrr1qlVJcw9eC6X+EDCW2QVFL0a5wdeKXrcLL6m/j6Nk4ZVCib5ElvB59STBS8B3NSlnm2CqrmAPIlEjJ4JBKXTM+4n+pySJJMPT8XdXQOeIwrQB8AOhT6Bl3NP0c2/DmDn07WJPKQPO8mPWksRLJXpRyFifdqfzI/Fz74t12HWxQbGi4/9raIlIj5EiAAy8GyYoTDsrY4nah14Uzpv5CVvA437qP+yBnR1g2XlmTfoRQaBOSuoE8moYl0QPHHFCb+K0oahhDsl/Y7CaI7ykub9SdwnmrqefIRp/n/VRNldDdpI=
    skip_cleanup: true
    on:
      repo: $TRAVIS_REPO_SLUG
      tags: true

  # Drafts a new release and attaches the release files...
  - provider: releases
    api_key:
      secure: nUm4FY23wMQeriLJ/SPJkWsA5cdz7y9zZVCI5wh8No6TjZXJKStWrUXdD/LYpix7OHnFNQeAGsNLnF8ShB7j290JaNWzThU9I3K5aTr9Jj8VwPt7g+dQZYFM1CWyKxdlPLDzTPTLespcu+9/Q5CjhyaiLVfcALIuZ3OB/4vbmmjTv1mJl3XiLBtQuPk9/itpn/6KR09CAdI+18DeDqxRGkAkz3v/GBnPrYtzsbV7ExbQz+qrbmKdrZ7Ni/v+Dm+OCBd7gtQWoNstUY2ZHsz2fTRqpXtLbziSgiSQ02LYvQojrQw8v7bkIkxe1eKHGdK3WhtgGi0kH35jK75C6gFAStfwvhVNh5/Nx1WHmTJVU0EFlyocCHDF85mhltQUaYWaqaayuTab9jsZ/65uRv3L9TlaPNrCY8jenmdKjwo5w7M3uvWx6/WrOFMJvInP8howqBMdWlrGZtomqd8uQFhFBJvV1uu9D07tfOPNy2FtVQlVd45+AvZ2LgN1I0v+H0qDo3mtypVdaj5JSzpM/cnEE0ah5yzf4FGSxZiOIhAvPKuRLEEzY5q5e26ztyVVYdmCX+mpiMp4KzzCvwWFHkDxa4O0OjOncl97g7aLAjZbuOM2dgbMKSPd5TMxDm2wZJ6giVw9ZXqY3YtVxmCfHMNILbPj8el+HfCbzYmIxGx1OnY=
    skip_cleanup: true
    target_commitish: $TRAVIS_COMMIT
    tag_name: $TRAVIS_TAG
    overwrite: true # overwrite existing release files
    file:
      - $OUTPUT_DIR/fontawesome.html
      - $OUTPUT_DIR/fontawesome.tid
    on:
      repo: $TRAVIS_REPO_SLUG
      tags: true
    name: TW5FontAwesome plugin release $TRAVIS_TAG
    body: 'see plugin history tiddler'
    draft: true
