#!/bin/sh
#
# release
# 
# generates release files:
#   editions\release\output\fontawesome.html -- the plugin demo wiki
#   editions\release\output\fontawesome.tid -- the plugin tiddler
#
tiddlywiki \
	editions/release \
	--verbose \
	--build release

